[package]
name = "l2"
version = "1.0.0"
cairo-version = "2.2.0"
authors = ["L2 Español, SEED Latam, StarknetEs - Starknet"]
description = "Workshop de 0 a Heroe. Envio de mensajes entre Ethereum <-> Starknet"

[dependencies]
starknet = ">=2.2.0"

[[target.starknet-contract]]
sierra = true